(in-package :chess)

(defconstant +king+ #\K)
(defconstant +queen+ #\Q)
(defconstant +rook+ #\R)
(defconstant +knight+ #\N)
(defconstant +bishop+ #\B)
(defconstant +pawn+ #\P)

(defconstant +white-king+ #\K)
(defconstant +white-queen+ #\Q)
(defconstant +white-rook+ #\R)
(defconstant +white-knight+ #\N)
(defconstant +white-bishop+ #\B)
(defconstant +white-pawn+ #\P)
(defconstant +white-pieces+ (list +white-king+ +white-queen+ +white-rook+ +white-knight+ +white-bishop+ +white-pawn+))

(defconstant +black-king+ #\k)
(defconstant +black-queen+ #\q)
(defconstant +black-rook+ #\r)
(defconstant +black-knight+ #\n)
(defconstant +black-bishop+ #\b)
(defconstant +black-pawn+ #\p)
(defconstant +black-pieces+ (list +black-king+ +black-queen+ +black-rook+ +black-knight+ +black-bishop+ +black-pawn+))

(defconstant +empty-square+ #\.)

(defconstant +white+ 'white)
(defconstant +black+ 'black)

(defconstant +north+ -10)
(defconstant +east+ 1)
(defconstant +south+ 10)
(defconstant +west+ -1)

(defconstant +piece-directions+
  (let* ((knight-directions (list (+ +north+ +north+ +east+)
                                  (+ +north+ +north+ +west+)
                                  (+ +north+ +east+ +east+)
                                  (+ +north+ +west+ +west+)
                                  (+ +south+ +south+ +east+)
                                  (+ +south+ +south+ +west+)
                                  (+ +south+ +east+ +east+)
                                  (+ +south+ +west+ +west+)))
         (rook-directions (list +north+ +east+ +south+ +west+))
         (bishop-directions (list (+ +north+ +east+) (+ +north+ +west+) (+ +south+ +east+) (+ +south+ +west+)))
         (queen-directions (concatenate 'list rook-directions bishop-directions))
         (king-directions queen-directions))
    (fset:map
     (+king+ king-directions)
     (+queen+ queen-directions)
     (+rook+ rook-directions)
     (+bishop+ bishop-directions)
     (+knight+ knight-directions)
     (+white-pawn+ (list +north+ (+ +north+ +north+) (+ +north+ +east+) (+ +north+ +west+)))
     (+black-pawn+ (list +south+ (+ +south+ +south+) (+ +south+ +east+) (+ +south+ +west+))))))
